version: "3.9"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data-volume:
